name: Publish

on:
  release:
    types: [created]

jobs:
  python-package:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build pytest

      - name: Build source and wheel
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Test built package
        run: |
          pip install dist/ms2rescore-*.whl
          # pytest
          ms2rescore --help

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-package
          path: dist/*

      - uses: pypa/gh-action-pypi-publish@release/v1

  windows-installer:
    runs-on: windows-latest
    needs: python-package
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install package and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . pyinstaller

      - name: Install Inno Setup
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install innosetup -y --allow-unofficial --force

      - name: Run pyinstaller
        run: pyinstaller ./ms2rescore.spec --clean --noconfirm

      - name: Test built exe
        run: dist/ms2rescore/ms2rescore.exe

      - name: Run Inno Setup
        run: ISCC.exe ./ms2rescore_innosetup.iss /DMyAppVersion=$(ms2rescore -v)

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.exe

      - name: Upload installer to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file_glob: true
          file: dist/*.exe
